### ISSUE TITLE
Migrate from cryptonite to crypton

### ISSUE THREAD

**Issue by ysangkok** [haskell-github-trust/smtp-mail#18]
As per https://github.com/commercialhaskell/stackage/issues/7474 it would be nice to migrate to crypton instead of cryptonite.

This package has already migrated to crypton-connection (because it was necessary, I think). So the maintainer (Kazu Yamamoto) of crypton is already trusted. Might as well migrate to crypton too since there might be additional problems with cryptonite at some point, and it won't receive updates.

**Comment by jamesdbrock** [comment]
Would you like to do that work @ysangkok ? I sent you an ownership invitation.

Before you do anything you should probably coördinate with @spencerjanssen because he's been responsible for this package lately.

**Comment by ysangkok** [comment]
Sure I can do that. If you wouldn't mind @spencerjanssen , I don't think there is much to coodinate? I'd simply make a new minor release.

**Comment by ysangkok** [comment]
fixed in https://github.com/haskell-github-trust/smtp-mail/commit/0cb568551a7a1e4aaaeb3aa71d993377f6c93499
