### ISSUE TITLE
Installation/Compilation Failure on smtp-mail 0.4.0.0 with GHC 9.6.5

### ISSUE THREAD

**Issue by smarwei** [haskell-github-trust/smtp-mail#8]
Hello,

I am experiencing issues when trying to install the `smtp-mail` package (version 0.4.0.0) on my system. The installation fails both on NixOS and on a fresh Ubuntu 24.04 VM.

**Steps to Reproduce:**
1. Run `cabal install smtp-mail`

**Expected Behavior:**
The package should install without errors.

**Actual Behavior:**
The build process fails with the following error message:

```
Build profile: -w ghc-9.6.5 -O1

Configuring library for smtp-mail-0.4.0.0..
Preprocessing library for smtp-mail-0.4.0.0..
Building library for smtp-mail-0.4.0.0..
[1 of 3] Compiling Network.Mail.SMTP.Auth ( Network/Mail/SMTP/Auth.hs, dist/build/Network/Mail/SMTP/Auth.o, dist/build/Network/Mail/SMTP/Auth.dyn_o )
[2 of 3] Compiling Network.Mail.SMTP.Types ( Network/Mail/SMTP/Types.hs, dist/build/Network/Mail/SMTP/Types.o, dist/build/Network/Mail/SMTP/Types.dyn_o )
[3 of 3] Compiling Network.Mail.SMTP ( Network/Mail/SMTP.hs, dist/build/Network/Mail/SMTP.o, dist/build/Network/Mail/SMTP.dyn_o )

Network/Mail/SMTP.hs:96:23: error: [GHC-83865]
    • Couldn't match expected type ‘Conn.TLSSettings’
                  with actual type ‘tls-2.0.6:Network.TLS.Parameters.Supported
                                    -> Conn.TLSSettings’
    • Probable cause: ‘Conn.TLSSettingsSimple’ is applied to too few arguments
      In the expression: Conn.TLSSettingsSimple False False False
      In an equation for ‘defaultTlsSettings’:
          defaultTlsSettings = Conn.TLSSettingsSimple False False False
   |
96 | defaultTlsSettings =  Conn.TLSSettingsSimple False False False
```

**System Information:**
- **OS:** NixOS (also tested on Ubuntu 24.04)
- **GHC Version:** 9.6.5
- **Cabal Version:** 3.10.3.0

**Comment by spencerjanssen** [comment]
Thanks for the report! Looks like we weren't compatible with the latest version of `crypton-connection`. I've revised the version bounds on `smtp-mail-0.4.0.0` as well as released `smtp-mail-0.4.0.1` with support for the new version of `crypton-connection`. A `cabal update` on your end should resolve the issue.
